name: Test summary example

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm build
      - name: Lint
        run: npm run lint-check && npm run format-check
      - name: Tests
        run: npm test 
      - name: Publish Test Results
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: ctrf/*.json
          summary-report: true
          test-report: false
          failed-report: false
          fail-rate-report: false
          flaky-report: false
          flaky-rate-report: false
          previous-results-report: true
          insights-report: true
          slowest-report: true
          upload-artifact: true
        if: always()
      - name: Post Results to Pull Request
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: ctrf/*.json
          pull-request-report: true
          summary-report: false
          annotate: false
