name: Test summary example

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run all
      - name: E2E test results
        run: npx ts-node src/cli.ts results "ctrf/*.json"
        if: always()
      - name: E2E flaky tests
        run: npx ts-node src/cli.ts flaky "ctrf/*.json"
        if: always()
      - name: E2E ai tests
        run: npx ts-node src/cli.ts ai "ctrf/*.json"
        if: always()
      - name: E2E failed tests
        run: npx ts-node src/cli.ts failed "ctrf/*.json"
        if: always()
      - name: E2E AI Consolidated
        run: npx ts-node src/cli.ts ai "ctrf/*.json" --consolidated
        if: always()
      - name: E2E failed tests consolidated
        run: npx ts-node src/cli.ts failed "ctrf/*.json" --consolidated
        if: always()
      - name: Publish Test Results
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: ctrf/*.json
          summary-report: true
          test-report: false
          failed-report: false
          fail-rate-report: false
          flaky-report: false
          flaky-rate-report: false
          previous-results-report: true
          insights-report: true
          slowest-report: true
          artifact: true
          upload-artifact: true
        if: always()
      - name: Post Results to Pull Request
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: ctrf/*.json
          pull-request-report: true
          summary-report: false
          annotate: false
