name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Build Check
        run: npm run build:check
      - name: Lint and Format Check
        run: npm run lint:check && npm run format:check
      - name: Run Tests
        run: npm test 
      - name: Publish Test Results
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: ctrf/*.json
          summary-report: true
          test-report: false
          failed-report: false
          fail-rate-report: false
          flaky-report: false
          flaky-rate-report: false
          previous-results-report: true
          insights-report: true
          slowest-report: true
          upload-artifact: true
          pull-request-report: true
          annotate: false
          overwrite-comment: true
